@urlDev=http://localhost:9000

### V1##########################################################


############################################################## CATEGORIES##################################################################

###### get all
# GET {{urlDev}}/v1/categories
GET http://localhost:9000/v1/categories

###Update the image of one category
POST http://localhost:9000/v1/categories/categoryImage/:id

### Insert One Category
POST http://localhost:9000/v1/categories/insertOne

### Update one Category following the id
PATCH http://localhost:9000/v1/categories/updateOne/:id

### Delete one category with the id
DELETE http://localhost:9000/v1/categories/deleteOne/:id
 
#######################SUPPLIERS###########################################################
GET http://localhost:9000/v1/suppliers

###Update the image of one category
POST http://localhost:9000/v1/suppliers/categoryImage/:id

### Insert One Category
POST http://localhost:9000/v1/suppliers/insertOne

### Update one Category following the id
PATCH http://localhost:9000/v1/suppliers/updateOne/:id

### Delete one category with the id
DELETE http://localhost:9000/v1/categories/deleteOne/:id
 
###################################EMPLOYEES################################################################
GET http://localhost:9000/v1/employees
### Get one employee following Id
GET http://localhost:9000/v1/employees/findById/:id



###################################PRODUCTS################################################################
GET http://localhost:9000/v1/products

###Find one employee following Id
GET http://localhost:9000/v1/products/findById/:id
#### Update one product
POST http://localhost:9000/v1/products/productImage/:id

### insert one employee
POST http://localhost:9000/v1/products/insertOne

## update image of one employee
POST http://localhost:9000/v1/products/productImage/:id

###delete one employee
DELETE http://localhost:9000/v1/products/deleteOne/63989ea171b18b684332143c

###----01---Get all products- container category and supplier- show stockTotal
GET http://localhost:9000/v1/products/01getStockTotal

### ---02--- Get products following categoryId
GET http://localhost:9000/v1/products/02getByCategoryId/:id

### ---03--- Get products following supplierId
GET http://localhost:9000/v1/products/03getBySupplierId/:id
 ###---04---Sorting products following price from low <-> high
###
GET http://localhost:9000/v1/products/04GetWithSortingPrice?sort=[low/high]

###---05---Sorting products following discount from low <-> high
###
GET http://localhost:9000/v1/products/05GetWithSortingDiscount?sort=[low/high]

### ---06---Lấy toàn bộ sản phẩm trong một danh mục nổi bật- theo id sản phẩm( hàng mới cập nhật)
GET http://localhost:9000/v1/products/getAll

###---07---Lấy toàn bộ sản phẩm có thêm stockTotal mô tả số lượng sản phẩm tồn kho và totalPrice- giá sản phẩm theo mỗi [size và màu sắc] có trường mảng Array- promotionPosition- chứa cụm từ "Giảm sốc trong ngày" hoặc "Gợi ý trong tuần"
GET http://localhost:9000/v1/products/07getByPromotionPosition?value=muahe

###---08---Lấy toàn bộ sản phẩm có thêm stockTotal mô tả số lượng sản phẩm tồn kho >0 và totalPrice- giá sản phẩm theo mỗi [size và màu sắc]
GET http://localhost:9000/v1/products/08getStockTotalMoreThan0
###################################EMPLOYEES################################################################
###Get all employees
###
GET http://localhost:9000/v1/employees

### Finding an employee with ID

GET http://localhost:9000/v1/employees/findById/:id

### update the image of the imployee with ID 

POST  http://localhost:9000/v1/employees/employeeImage/:id

### Add a new employee

GET http://localhost:9000/v1/employees/insertOne

###Update info of one employee- if update email, after update employee, We continue to update email in collection Logins

PATCH http://localhost:9000/v1/employees/updateOne/:id

### Delete one employee, if the employee have an account login, we have to delete it
DELETE http://localhost:9000/v1/employees/deleteOne/:id






###################################LOGINS################################################################
###Check for login with email and password
POST http://localhost:9000/v1/login
### get all
GET http://localhost:9000/v1/login/all

###Find one employee following Id
GET http://localhost:9000/v1/employees/findById/:id

###Find one employee following email
GET http://localhost:9000/v1/employees/findByEmail/:email
#### Update the account login, if update email, we have to update email into collection Employees.
PATCH  http://localhost:9000/v1/login/updateOne/:id
### insert one employee, check the existing of the email in collection Employee, if don't have, then create a new employee having the email
POST http://localhost:9000/v1/login/insertOne
###delete one account login
DELETE http://localhost:9000/v1/login/deleteOne/:id



