const URL_DATA_SERVER = "mongodb://127.0.0.1:27017/";
const PATH_FOLDER_PUBLIC_UPLOAD = "./public/uploads";
const PATH_FOLDER_IMAGES = "/images";
const FOLDER_INITIATION = "initiation";
const COLLECTION_CATEGORIES = "categories";
const COLLECTION_SUPPLIERS = "suppliers";
const COLLECTION_PRODUCTS = 'products';
const COLLECTION_EMPLOYEES = 'employees';
const COLLECTION_ORDERS = 'orders';
const COLLECTION_LOGINS = "logins";
const COLLECTION_SLIDES = "slides";
const COLLECTION_TRANSPORTATIONS = "transportations";

module.exports = {
  URL_DATA_SERVER,
  PATH_FOLDER_PUBLIC_UPLOAD,
  PATH_FOLDER_IMAGES,
  FOLDER_INITIATION,
  COLLECTION_CATEGORIES,
  COLLECTION_SUPPLIERS,
  COLLECTION_PRODUCTS,
  COLLECTION_EMPLOYEES,
  COLLECTION_ORDERS,
  COLLECTION_LOGINS,
  COLLECTION_TRANSPORTATIONS,
  COLLECTION_SLIDES
};
